//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Controls/PlayerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerActions"",
    ""maps"": [
        {
            ""name"": ""InGamePlayer"",
            ""id"": ""a8c863e6-7468-4088-b751-e013c224eaed"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""7be02fc2-062b-4735-b579-ad26537dc9bd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""fd33c9a9-15e9-43a8-a9c7-26676aacb9d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""29555f54-ec79-4fe2-8189-e811daebfb85"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e5c82521-f918-4535-8fda-dc1393ac2f49"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0143a6fc-5359-4594-8554-b83a84f065d1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8913f87e-f038-4de0-aede-e37eed65cbef"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e84704f1-845e-4a61-b1d1-6f7f2276435d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""55454851-fc8d-471c-b02d-5183bcdf08bc"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""300e4cb4-1a1d-4385-8fe5-450e8c61f246"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a85f927-5191-4e51-b022-332ba149ae33"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // InGamePlayer
        m_InGamePlayer = asset.FindActionMap("InGamePlayer", throwIfNotFound: true);
        m_InGamePlayer_Movement = m_InGamePlayer.FindAction("Movement", throwIfNotFound: true);
        m_InGamePlayer_Jump = m_InGamePlayer.FindAction("Jump", throwIfNotFound: true);
        m_InGamePlayer_Attack = m_InGamePlayer.FindAction("Attack", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InGamePlayer
    private readonly InputActionMap m_InGamePlayer;
    private IInGamePlayerActions m_InGamePlayerActionsCallbackInterface;
    private readonly InputAction m_InGamePlayer_Movement;
    private readonly InputAction m_InGamePlayer_Jump;
    private readonly InputAction m_InGamePlayer_Attack;
    public struct InGamePlayerActions
    {
        private @PlayerActions m_Wrapper;
        public InGamePlayerActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_InGamePlayer_Movement;
        public InputAction @Jump => m_Wrapper.m_InGamePlayer_Jump;
        public InputAction @Attack => m_Wrapper.m_InGamePlayer_Attack;
        public InputActionMap Get() { return m_Wrapper.m_InGamePlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGamePlayerActions set) { return set.Get(); }
        public void SetCallbacks(IInGamePlayerActions instance)
        {
            if (m_Wrapper.m_InGamePlayerActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_InGamePlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_InGamePlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_InGamePlayerActionsCallbackInterface.OnMovement;
                @Jump.started -= m_Wrapper.m_InGamePlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_InGamePlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_InGamePlayerActionsCallbackInterface.OnJump;
                @Attack.started -= m_Wrapper.m_InGamePlayerActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_InGamePlayerActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_InGamePlayerActionsCallbackInterface.OnAttack;
            }
            m_Wrapper.m_InGamePlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
            }
        }
    }
    public InGamePlayerActions @InGamePlayer => new InGamePlayerActions(this);
    public interface IInGamePlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
    }
}
